-- Lisää DROP TABLE lauseet tähän tiedostoon

DROP TABLE IF EXISTS Category CASCADE;

DROP TABLE IF EXISTS Ingredient CASCADE;

DROP TABLE IF EXISTS Person CASCADE;

DROP TABLE IF EXISTS Recipe CASCADE;

DROP TABLE IF EXISTS Addtable CASCADE;
